version: '3.8'

services:
  # MySQL Database for Skier Service
  skier-db:
    container_name: db-skier
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: skierdb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3308:3306"
    volumes:
      - data-skier:/var/lib/mysql
    restart: always
    networks:
      - ski-management-network

  # MySQL Database for Instructor Service
  instructor-db:
    container_name: db-instructor
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: instructordb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3307:3306"
    volumes:
      - data-instructor:/var/lib/mysql
    restart: always
    networks:
      - ski-management-network

  # MySQL Database for Course Service
  course-db:
    container_name: db-course
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: coursedb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3309:3306"
    volumes:
      - data-course:/var/lib/mysql
    restart: always
    networks:
      - ski-management-network

  # MySQL Database for Subscription Service
  subscription-db:
    container_name: db-subscription
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: subscriptiondb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3310:3306"
    volumes:
      - data-subscription:/var/lib/mysql
    restart: always
    networks:
      - ski-management-network

  # MySQL Database for Registration Service
  registration-db:
    container_name: db-registration
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: registrationdb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3311:3306"
    volumes:
      - data-registration:/var/lib/mysql
    restart: always
    networks:
      - ski-management-network

  # MySQL Database for Piste Service
  piste-db:
    container_name: db-piste
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: pistedb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3312:3306"
    volumes:
      - data-piste:/var/lib/mysql
    restart: always
    networks:
      - ski-management-network

  # Skier Service
  skier-service:
    container_name: service-skier
    image: maleklabidi/skier-management-service:latest
    ports:
      - "8088:8080"
    depends_on:
      - skier-db
      - gateway-service
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-skier:3306/skierdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - ski-management-network
    restart: unless-stopped

  # Instructor Service
  instructor-service:
    container_name: service-instructor
    image: maleklabidi/instructor-management-service:latest
    ports:
      - "8081:8080"
    depends_on:
      - instructor-db
      - gateway-service
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-instructor:3306/instructordb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - ski-management-network
    restart: unless-stopped

  # Course Service
  course-service:
    container_name: service-course
    image: maleklabidi/course-management-service:latest
    ports:
      - "8082:8080"
    depends_on:
      - course-db
      - gateway-service
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-course:3306/coursedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - ski-management-network
    restart: unless-stopped

  # Subscription Service
  subscription-service:
    container_name: service-subscription
    image: maleklabidi/subscription-management-service:latest
    ports:
      - "8085:8080"
    depends_on:
      - db-subscription
      - gateway-service
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-subscription:3306/subscriptiondb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - ski-management-network
    restart: unless-stopped

  # Registration Service
  registration-service:
    container_name: service-registration
    image: maleklabidi/registration-management-service:latest
    ports:
      - "8086:8080"
    depends_on:
      - db-registration
      - gateway-service
      - discovery-service
      - skier-service
      - course-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-registration:3306/registrationdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - ski-management-network
    restart: unless-stopped

  # Piste Service
  piste-service:
    container_name: service-piste
    image: maleklabidi/piste-management-service:latest
    ports:
      - "8087:8080"
    depends_on:
      - db-piste
      - gateway-service
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-piste:3306/pistedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - ski-management-network
    restart: unless-stopped

  # Discovery Service
  discovery-service:
    container_name: service-discovery
    image: maleklabidi/discovery-service:latest
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ski-management-network
    restart: unless-stopped

  # Gateway Service
  gateway-service:
    container_name: service-gateway
    image: maleklabidi/api-gateway:latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-service
    networks:
      - ski-management-network
    restart: unless-stopped

# Network for all services
networks:
  ski-management-network:
    driver: bridge

# Volumes for database data persistence
volumes:
  data-skier:
    driver: local
  data-instructor:
    driver: local
  data-course:
    driver: local
  data-subscription:
    driver: local
  data-registration:
    driver: local
  data-piste:
    driver: local
