#version: '3.8'

services:


  # MySQL Database for Course Service
  # Cette section configure un conteneur pour la base de données MySQL du service "Course".
  course-db:
    container_name: course-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: coursedb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3309:3306"
    volumes:
      - course_db_data:/var/lib/mysql
    restart: always
    networks:
      - ski-management-network




  #Discovery Service
  # Cette section configure le service discovery.
  discovery-service:
    container_name: discovery-service
    image: jouhaynacheikh/discovery-service:1.0
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ski-management-network
    restart: unless-stopped

  #Gateway Service
  # Cette section configure le service gateway.
  gateway-service:
    container_name: gateway-service
    image: jouhaynacheikh/api-gateway:1.0
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-service
    networks:
      - ski-management-network
    restart: unless-stopped

  # Course Service
  # Cette section configure le service course. Ce service dépend de la base de données "course-db".
  course-service:
    container_name: course-service
    image: jouhaynacheikh/course-management-service:1.0
    ports:
      - "8084:8080"
    depends_on:
      - course-db
      - gateway-service
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://course-db:3306/coursedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - ski-management-network
    restart: unless-stopped

# Réseau pour les services
networks:
  ski-management-network:
    driver: bridge

# Définition des volumes pour persister les données des bases de données.
volumes:
  course_db_data:
    driver: local
