version: '3.8'

services:

  # MySQL Database for Skier Service
  skier-db:
     container_name: skier-db
     image: mysql:8.0
     environment:
       MYSQL_DATABASE: skierdb
       MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
     ports:
       - "3308:3306"
     volumes:
       - skier_db_data:/var/lib/mysql
     restart: always
     networks:
       - ski-management-network

  # MySQL Database for Subscription Service
  subscription-db:
   container_name: subscription-db
   image: mysql:8.0
   environment:
     MYSQL_DATABASE: subscriptiondb
     MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
   ports:
     - "3310:3306"
   volumes:
     - subscription_db_data:/var/lib/mysql
   restart: always
   networks:
     - ski-management-network


  # Discovery Service
  discovery-service:
    container_name: discovery-service
    image: 192.168.50.4:8082/discovery-service:1.0
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ski-management-network
    restart: unless-stopped

  # Gateway Service
  gateway-service:
    container_name: gateway-service
    image: 192.168.50.4:8082/api-gateway:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - discovery-service
    networks:
      - ski-management-network
    restart: unless-stopped

  # Subscription Service
  subscription-service:
    container_name: subscription-service
    image: 192.168.50.4:8082/subscription-management-service:1.0
    ports:
      - "8085:8080"
    depends_on:
      - subscription-db
      - gateway-service
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://subscription-db:3306/subscriptiondb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - ski-management-network
    restart: unless-stopped
    
 # Skier Service
  skier-service:
   container_name: skier-service
   image: 192.168.50.4:8082/skier-management-service:1.0
   ports:
     - "8088:8080"
   depends_on:
     - skier-db
     - gateway-service
     - discovery-service
     - subscription-service

   environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://skier-db:3306/skierdb
     SPRING_DATASOURCE_USERNAME: root
     SPRING_DATASOURCE_PASSWORD:
     SPRING_JPA_SHOW_SQL: "true"
   networks:
     - ski-management-network
   restart: unless-stopped


# Network configuration
networks:
  ski-management-network:
    driver: bridge

# Volume configuration for database persistence
volumes:
  skier_db_data:
    driver: local
  subscription_db_data:
    driver: local
