version: '3.8'

services:


  # MySQL Database for Piste Service
  piste-db:
    container_name: piste-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: pistedb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3312:3306"
    volumes:
      - piste_db_data:/var/lib/mysql
    restart: always
    networks:
      - ski-management-network


  # Discovery Service
  discovery-service:
    container_name: discovery-service
    image: chaimaaa20/discovery-service:1.0
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ski-management-network
    restart: unless-stopped

  # Gateway Service
  gateway-service:
    container_name: gateway-service
    image: chaimaaa20/api-gateway:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - discovery-service
    networks:
      - ski-management-network
    restart: unless-stopped

  # Piste Service
  piste-service:
    container_name: piste-service
    image: chaimaaa20/piste-management-service:1.0
    ports:
      - "8087:8080"
    depends_on:
      - piste-db
      - gateway-service
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://piste-db:3306/pistedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - ski-management-network
    restart: unless-stopped


# Network configuration
networks:
  ski-management-network:
    driver: bridge

# Volume configuration for database persistence
volumes:
  piste_db_data:
    driver: local