version: '3.8'

services:
  # Subscription Service
  # Cette section configure le service subscription. Ce service dépend de la base de données "subscription-db".
  subscription-service:
    container_name: subscription-service
    image: maherkr/subscription-management-service:1.0.0
    ports:
      - "8085:8080"
    depends_on:
      - subscription-db
      - gateway-service
      - discovery-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://subscription-db:3306/subscriptiondb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - ski-management-network
    restart: unless-stopped

  # Discovery Service
  # Cette section configure le service discovery.
  discovery-service:
    container_name: discovery-service
    image: maherkr/discovery-service:1.0.0
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - ski-management-network
    restart: unless-stopped

  # Gateway Service
  # Cette section configure le service gateway.
  gateway-service:
    container_name: gateway-service
    image: maherkr/gateway-service:1.0.0
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - discovery-service
    networks:
      - ski-management-network
    restart: unless-stopped

  # MySQL Database for Subscription Service
  # Cette section configure un conteneur pour la base de données MySQL du service "Subscription".
  subscription-db:
    container_name: subscription-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: subscriptiondb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3310:3306"
    volumes:
      - subscription_db_data:/var/lib/mysql
    restart: always
    networks:
      - ski-management-network

# Réseau pour les services
networks:
  ski-management-network:
    driver: bridge

# Définition des volumes pour persister les données des bases de données.
volumes:
  subscription_db_data:
    driver: local
