version: '3.8'

services:
  # MySQL Database for Course Service
  course-db:
    container_name: course-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: coursedb
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - "3309:3306"
    volumes:
      - course_db_data:/var/lib/mysql
    restart: always
    networks:
      - ski-management-network

  # Discovery Service
  discovery-service:
    container_name: discovery-service
    image: 192.168.50.4:8082/docker-hosted/discovery-service:1.0
    ports:
      - "8761:8761"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - ski-management-network
    restart: unless-stopped

  # Gateway Service
  gateway-service:
    container_name: gateway-service
    image: 192.168.50.4:8082/docker-hosted/api-gateway:1.0
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - discovery-service
    networks:
      - ski-management-network
    restart: unless-stopped

  # Course Service
  course-service:
    container_name: course-service
    image: 192.168.50.4:8082/docker-hosted/course-management-service:1.0
    ports:
      - "8084:8080"
    depends_on:
      - course-db
      - discovery-service
      - gateway-service

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://course-db:3306/coursedb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ''
      SPRING_JPA_SHOW_SQL: "true"
    networks:
      - ski-management-network
    restart: unless-stopped

# Network configuration
networks:
  ski-management-network:
    driver: bridge

# Volume configuration for database persistence
volumes:
  course_db_data:
    driver: local
